[package]
name = "microservices"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = { version = "0.23.0", features = ["tokio-comp"] }
tokio = { version = "1.28", features = ["full"] }
sentry = { version = "0.31.0", features = ["debug-logs"] }
dotenv = "0.15.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"